#! /bin/bash

# This script is used to define paths that will be used
# in other scripts. It must be sourced at the beginning
# of every other scripts.

# DO NOT edit this file unless you are sure of what you do.
# Editing these variables will impact the hierarchy of projects.

source ./environment/project_root.sh

# Base directories
export SCRIPTSDIR="$BASEDIR/scripts"
export RESOURCESDIR="$BASEDIR/resources"
export PROJECTSDIR="$BASEDIR/projects"
#export ENVLOGDIR="$BASEDIR/env_logs"

# Resources directories
export KERNELSOURCES=$RESOURCESDIR/linux_kernel
export FSSOURCES=$RESOURCESDIR/file_system

# Resources files
export BOOTLOADERHEADER=$RESOURCESDIR/boot_loader/zynq_common.h
export DEVICETREEDTS=$RESOURCESDIR/device_tree/zynq_devicetree.dts

