#! /bin/bash

# This script is used to define URLs where sources
# can be found.

# DO NOT edit this file unless you are sure of what you do.
# Editing these variables will impact the hierarchy of projects.

export LINUXKERNELURL=https://github.com/Xilinx/linux-xlnx.git
export BUILDROOTURL=git://git.buildroot.net/buildroot

