#! /bin/bash

# This script is used to define URLs where sources
# can be found.

# DO NOT edit this file unless there is a problem with original repositories

export LINUXKERNELURL=https://github.com/Xilinx/linux-xlnx.git
export BUILDROOTURL=git://git.buildroot.net/buildroot
export BOOTLOADERURL=https://github.com/Xilinx/u-boot-xlnx.git
export DEVICETREEURL=https://github.com/Xilinx/device-tree-xlnx.git

